name: CI/CD Staging

on:
  push:
    branches:
      - develop

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies, test and build
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
      - name: Run test
        run: yarn test
  # deploy:
  #   name: CD Pipeline
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.8]
  #       node-version: ['12.x']
  #       appname: ['api']
  #       deploy-group: ['develop']
  #       s3-bucket: ['aws-deployments-bot-discord-develop']
  #       s3-filename: ['bot-discord-develop-${{ github.sha }}']
  #   needs: buildAndTest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     # Initialize Node.js
  #     - name: Install Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     # Install project dependencies and build
  #     - name: Install dependencies
  #       run: npm install
  #     # Prevent files from having a timestamp before 1980
  #     - name: Patch dependencies
  #       run: find ./node_modules -mtime +10950 -exec touch {} \;
  #     - name: Run build:keys
  #       run: npm run build:keys
  #     - name: Run build
  #       run: npm run build
  #     # Install AWS CLI 2
  #     - name: Install AWS CLI 2
  #       run: |
  #         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  #         unzip awscliv2.zip
  #         sudo ./aws/install --update
  #     # Configure AWS credentials
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: eu-west-3
  #     # Deploy push to AWS S3
  #     - name: AWS Deploy push
  #       run: |
  #         aws deploy push \
  #         --application-name ${{ matrix.appname }} \
  #         --description "This is a revision for the ${{ matrix.appname }}-${{ github.sha }}" \
  #         --ignore-hidden-files \
  #         --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
  #         --source .
  #     # Create deployment to CodeDeploy
  #     - name: AWS Create Deployment
  #       run: |
  #         aws deploy create-deployment \
  #          --application-name ${{ matrix.appname }} \
  #          --deployment-config-name CodeDeployDefault.OneAtATime \
  #          --deployment-group-name ${{ matrix.deploy-group }} \
  #          --file-exists-behavior OVERWRITE \
  #          --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \
  #          --ignore-application-stop-failures \
